### ISSUE TITLE
[Homonynous project] have got a problem when using Archsim

### ISSUE THREAD

**Issue by starz009** [christophe-riolo/Archsim#1]
have got a problem when using Archsim

When I connect model zone, window to the Networker, it always comes: You model unit system must be in meters. However, my unit in rhino is in meters. 

![image](https://user-images.githubusercontent.com/35608424/38374141-37407afc-38f3-11e8-863e-cca5f71a489c.png)

**Comment by christophe-riolo** [comment]
I am not familiar with this project anymore but I'll have a look!

**Comment by christophe-riolo** [comment]
Wait, I thought this didn't look familiar, there's a confusion, this is not the program you are using. You are using a *building* archtecture simulator, that's a processor/memory communication simulator, nothing in common except the name, sorry :)
